"""rename address

Revision ID: 4dc90bd1b604
Revises: bc8770c40376
Create Date: 2024-06-28 15:02:29.379745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc90bd1b604'
down_revision = 'bc8770c40376'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('department', sa.Column('location', sa.String(), nullable=False))
#     op.drop_column('department', 'address')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('department', sa.Column('address', sa.VARCHAR(), nullable=True))
#     op.drop_column('department', 'location')
#     # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
